package com.eastng.football.core.entity.team;

public class TeamSeason {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_season.ID
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_season.TEAM_NO
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    private String teamNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_season.SEASON_NO
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    private String seasonNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_season.TEAM_NAME
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    private String teamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_season.POINT
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_season.RANK
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    private Integer rank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_season.GOALS
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    private Integer goals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_season.FUMBLE
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    private Integer fumble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_season.GOAL_DIFF
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    private Integer goalDiff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_season.PROMOTE
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    private String promote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_season.ID
     *
     * @return the value of t_team_season.ID
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_season.ID
     *
     * @param id the value for t_team_season.ID
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_season.TEAM_NO
     *
     * @return the value of t_team_season.TEAM_NO
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public String getTeamNo() {
        return teamNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_season.TEAM_NO
     *
     * @param teamNo the value for t_team_season.TEAM_NO
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public void setTeamNo(String teamNo) {
        this.teamNo = teamNo == null ? null : teamNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_season.SEASON_NO
     *
     * @return the value of t_team_season.SEASON_NO
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public String getSeasonNo() {
        return seasonNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_season.SEASON_NO
     *
     * @param seasonNo the value for t_team_season.SEASON_NO
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public void setSeasonNo(String seasonNo) {
        this.seasonNo = seasonNo == null ? null : seasonNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_season.TEAM_NAME
     *
     * @return the value of t_team_season.TEAM_NAME
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_season.TEAM_NAME
     *
     * @param teamName the value for t_team_season.TEAM_NAME
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_season.POINT
     *
     * @return the value of t_team_season.POINT
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_season.POINT
     *
     * @param point the value for t_team_season.POINT
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_season.RANK
     *
     * @return the value of t_team_season.RANK
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_season.RANK
     *
     * @param rank the value for t_team_season.RANK
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_season.GOALS
     *
     * @return the value of t_team_season.GOALS
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public Integer getGoals() {
        return goals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_season.GOALS
     *
     * @param goals the value for t_team_season.GOALS
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public void setGoals(Integer goals) {
        this.goals = goals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_season.FUMBLE
     *
     * @return the value of t_team_season.FUMBLE
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public Integer getFumble() {
        return fumble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_season.FUMBLE
     *
     * @param fumble the value for t_team_season.FUMBLE
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public void setFumble(Integer fumble) {
        this.fumble = fumble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_season.GOAL_DIFF
     *
     * @return the value of t_team_season.GOAL_DIFF
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public Integer getGoalDiff() {
        return goalDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_season.GOAL_DIFF
     *
     * @param goalDiff the value for t_team_season.GOAL_DIFF
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public void setGoalDiff(Integer goalDiff) {
        this.goalDiff = goalDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_season.PROMOTE
     *
     * @return the value of t_team_season.PROMOTE
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public String getPromote() {
        return promote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_season.PROMOTE
     *
     * @param promote the value for t_team_season.PROMOTE
     *
     * @mbggenerated Fri Aug 26 15:31:36 CST 2016
     */
    public void setPromote(String promote) {
        this.promote = promote == null ? null : promote.trim();
    }
}