package com.eastng.football.core.service.match.persistence;

import com.eastng.football.core.entity.match.District;
import com.eastng.football.core.entity.match.DistrictExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_district
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    int countByExample(DistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_district
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    int deleteByExample(DistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_district
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_district
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    int insert(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_district
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    int insertSelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_district
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    List<District> selectByExample(DistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_district
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    District selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_district
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") District record, @Param("example") DistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_district
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    int updateByExample(@Param("record") District record, @Param("example") DistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_district
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    int updateByPrimaryKeySelective(District record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_district
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    int updateByPrimaryKey(District record);
}