package com.eastng.football.core.service.match.persistence;

import org.apache.ibatis.annotations.Delete;

import com.eastng.football.core.entity.match.LeagueInfo;

public interface LeagueInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    int insert(LeagueInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    int insertSelective(LeagueInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    LeagueInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    int updateByPrimaryKeySelective(LeagueInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    int updateByPrimaryKey(LeagueInfo record);
    
    /**
     * 清空T_LEAGUE_INFO表数据
     * 谨慎使用该接口
     * @return
     */
    @Delete("delete from t_league_info")
    int deleteAll();
}