package com.eastng.football.core.service.match.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;

import com.eastng.football.core.entity.match.LeagueInfo;
import com.eastng.football.core.entity.match.LeagueInfoExample;

public interface LeagueInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:11:52 CST 2016
     */
    int countByExample(LeagueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:11:52 CST 2016
     */
    int deleteByExample(LeagueInfoExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    int insert(LeagueInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    int insertSelective(LeagueInfo record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:11:52 CST 2016
     */
    List<LeagueInfo> selectByExample(LeagueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    LeagueInfo selectByPrimaryKey(Long id);

    /**
     * 根据赛事编号查询该赛事详情
     * @param leagueNo
     * @return LeagueInfo
     */
    LeagueInfo selectByLeagueNo(String leagueNo);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:11:52 CST 2016
     */
    int updateByExampleSelective(@Param("record") LeagueInfo record, @Param("example") LeagueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:11:52 CST 2016
     */
    int updateByExample(@Param("record") LeagueInfo record, @Param("example") LeagueInfoExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    int updateByPrimaryKeySelective(LeagueInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    int updateByPrimaryKey(LeagueInfo record);
    
    /**
     * 清空T_LEAGUE_INFO表数据
     * 谨慎使用该接口
     * @return
     */
    @Delete("delete from t_league_info")
    int deleteAll();
}