package com.eastng.football.core.service.match.persistence;

import java.util.List;
import java.util.Map;

import com.eastng.football.core.entity.match.LeagueSeason;

public interface LeagueSeasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_season
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_season
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    int insert(LeagueSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_season
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    int insertSelective(LeagueSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_season
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    LeagueSeason selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_season
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    int updateByPrimaryKeySelective(LeagueSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_season
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    int updateByPrimaryKey(LeagueSeason record);
    
    /**
     * 根据条件查询赛季信息
     * @param seasonNo
     * @return
     */
    List<LeagueSeason> selectByCondition(LeagueSeason record);
    
    /**
     * 根据联赛Number 获取最新的联赛
     * 
     * @param leagueNo
     * @return
     * @author laughing
     */
   // @Select("select * from t_league_season where LEAGUE_NO =#{0} order by  SEASON_NO desc limit 1")
    LeagueSeason selectMaxLeagueSeasonByLeagueNo(Map<String, String> params);
}