package com.eastng.football.core.service.match.persistence;

import com.eastng.football.core.entity.match.TeamCupSeason;

public interface TeamCupSeasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_cup_season
     *
     * @mbggenerated Tue Jan 05 10:40:54 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_cup_season
     *
     * @mbggenerated Tue Jan 05 10:40:54 CST 2016
     */
    int insert(TeamCupSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_cup_season
     *
     * @mbggenerated Tue Jan 05 10:40:54 CST 2016
     */
    int insertSelective(TeamCupSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_cup_season
     *
     * @mbggenerated Tue Jan 05 10:40:54 CST 2016
     */
    TeamCupSeason selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_cup_season
     *
     * @mbggenerated Tue Jan 05 10:40:54 CST 2016
     */
    int updateByPrimaryKeySelective(TeamCupSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_cup_season
     *
     * @mbggenerated Tue Jan 05 10:40:54 CST 2016
     */
    int updateByPrimaryKey(TeamCupSeason record);
}