package com.eastng.football.core.service.match.persistence;

import java.util.List;

import com.eastng.football.core.entity.match.TeamSeasonScore;

public interface TeamSeasonScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_season_score
     *
     * @mbggenerated Wed Aug 10 17:13:58 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_season_score
     *
     * @mbggenerated Wed Aug 10 17:13:58 CST 2016
     */
    int insert(TeamSeasonScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_season_score
     *
     * @mbggenerated Wed Aug 10 17:13:58 CST 2016
     */
    int insertSelective(TeamSeasonScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_season_score
     *
     * @mbggenerated Wed Aug 10 17:13:58 CST 2016
     */
    TeamSeasonScore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_season_score
     *
     * @mbggenerated Wed Aug 10 17:13:58 CST 2016
     */
    int updateByPrimaryKeySelective(TeamSeasonScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_season_score
     *
     * @mbggenerated Wed Aug 10 17:13:58 CST 2016
     */
    int updateByPrimaryKey(TeamSeasonScore record);
    
    /**
     * 根据条件查询某一球队在某个赛季某一轮的积分信息
     * @param record
     * @return
     */
    TeamSeasonScore selectOneByCondition(TeamSeasonScore record);
    
    /**
     * 根据条件查询积分信息
     * @param record
     * @return
     */
    List<TeamSeasonScore> selectByCondition(TeamSeasonScore record);
    
    /**
     * 查询赛季最新积分榜
     * @param seasonNo 赛季编号
     * @return
     */
    List<TeamSeasonScore> selectScoreBoardBySeasonNo(String seasonNo);
}