package com.eastng.football.core.service.match.persistence;

import com.eastng.football.core.entity.match.TeamLeagueSeason;

public interface TeamLeagueSeasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_league_season
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_league_season
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    int insert(TeamLeagueSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_league_season
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    int insertSelective(TeamLeagueSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_league_season
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    TeamLeagueSeason selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_league_season
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    int updateByPrimaryKeySelective(TeamLeagueSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_league_season
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    int updateByPrimaryKey(TeamLeagueSeason record);
}