package com.eastng.football.core.service.match.persistence;

import com.eastng.football.core.entity.match.Team;
import com.eastng.football.core.entity.match.TeamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jan 03 13:46:51 CST 2016
     */
    int countByExample(TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jan 03 13:46:51 CST 2016
     */
    int deleteByExample(TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jan 03 13:46:51 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jan 03 13:46:51 CST 2016
     */
    int insert(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jan 03 13:46:51 CST 2016
     */
    int insertSelective(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jan 03 13:46:51 CST 2016
     */
    List<Team> selectByExample(TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jan 03 13:46:51 CST 2016
     */
    Team selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jan 03 13:46:51 CST 2016
     */
    int updateByExampleSelective(@Param("record") Team record, @Param("example") TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jan 03 13:46:51 CST 2016
     */
    int updateByExample(@Param("record") Team record, @Param("example") TeamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jan 03 13:46:51 CST 2016
     */
    int updateByPrimaryKeySelective(Team record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team
     *
     * @mbggenerated Sun Jan 03 13:46:51 CST 2016
     */
    int updateByPrimaryKey(Team record);
    
    /**
     * 批量插入球队记录
     * @param list
     * @return
     */
    int batchInsert(List<Team> list);
}