package com.eastng.football.core.service.match.persistence;

import com.eastng.football.core.entity.match.TeamCupScore;

public interface TeamCupScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_cup_score
     *
     * @mbggenerated Wed Aug 10 17:16:54 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_cup_score
     *
     * @mbggenerated Wed Aug 10 17:16:54 CST 2016
     */
    int insert(TeamCupScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_cup_score
     *
     * @mbggenerated Wed Aug 10 17:16:54 CST 2016
     */
    int insertSelective(TeamCupScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_cup_score
     *
     * @mbggenerated Wed Aug 10 17:16:54 CST 2016
     */
    TeamCupScore selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_cup_score
     *
     * @mbggenerated Wed Aug 10 17:16:54 CST 2016
     */
    int updateByPrimaryKeySelective(TeamCupScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_team_cup_score
     *
     * @mbggenerated Wed Aug 10 17:16:54 CST 2016
     */
    int updateByPrimaryKey(TeamCupScore record);
}