package com.eastng.football.core.service.lottery.persistence;

import com.eastng.football.core.entity.lottery.Odds;
import com.eastng.football.core.entity.lottery.OddsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OddsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_odds
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    int countByExample(OddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_odds
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    int deleteByExample(OddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_odds
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_odds
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    int insert(Odds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_odds
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    int insertSelective(Odds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_odds
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    List<Odds> selectByExample(OddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_odds
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    Odds selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_odds
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    int updateByExampleSelective(@Param("record") Odds record, @Param("example") OddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_odds
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    int updateByExample(@Param("record") Odds record, @Param("example") OddsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_odds
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    int updateByPrimaryKeySelective(Odds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_odds
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    int updateByPrimaryKey(Odds record);
}