package com.eastng.football.core.entity.match;

public class District {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_district.ID
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_district.DISTRICT_NO
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    private String districtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_district.DISTRICT_NAME
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    private String districtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_district.DISTRICT_LEVEL
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    private String districtLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_district.PARENT_DISTRICT_NO
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    private String parentDistrictNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_district.FIRST_LETTER
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    private String firstLetter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_district.ID
     *
     * @return the value of t_district.ID
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_district.ID
     *
     * @param id the value for t_district.ID
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_district.DISTRICT_NO
     *
     * @return the value of t_district.DISTRICT_NO
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    public String getDistrictNo() {
        return districtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_district.DISTRICT_NO
     *
     * @param districtNo the value for t_district.DISTRICT_NO
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    public void setDistrictNo(String districtNo) {
        this.districtNo = districtNo == null ? null : districtNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_district.DISTRICT_NAME
     *
     * @return the value of t_district.DISTRICT_NAME
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_district.DISTRICT_NAME
     *
     * @param districtName the value for t_district.DISTRICT_NAME
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName == null ? null : districtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_district.DISTRICT_LEVEL
     *
     * @return the value of t_district.DISTRICT_LEVEL
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    public String getDistrictLevel() {
        return districtLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_district.DISTRICT_LEVEL
     *
     * @param districtLevel the value for t_district.DISTRICT_LEVEL
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    public void setDistrictLevel(String districtLevel) {
        this.districtLevel = districtLevel == null ? null : districtLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_district.PARENT_DISTRICT_NO
     *
     * @return the value of t_district.PARENT_DISTRICT_NO
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    public String getParentDistrictNo() {
        return parentDistrictNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_district.PARENT_DISTRICT_NO
     *
     * @param parentDistrictNo the value for t_district.PARENT_DISTRICT_NO
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    public void setParentDistrictNo(String parentDistrictNo) {
        this.parentDistrictNo = parentDistrictNo == null ? null : parentDistrictNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_district.FIRST_LETTER
     *
     * @return the value of t_district.FIRST_LETTER
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    public String getFirstLetter() {
        return firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_district.FIRST_LETTER
     *
     * @param firstLetter the value for t_district.FIRST_LETTER
     *
     * @mbggenerated Mon Jan 25 22:43:53 CST 2016
     */
    public void setFirstLetter(String firstLetter) {
        this.firstLetter = firstLetter == null ? null : firstLetter.trim();
    }
}