package com.eastng.football.core.entity.match;

import java.util.ArrayList;
import java.util.List;

public class LeagueInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    public LeagueInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLeagueNoIsNull() {
            addCriterion("LEAGUE_NO is null");
            return (Criteria) this;
        }

        public Criteria andLeagueNoIsNotNull() {
            addCriterion("LEAGUE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andLeagueNoEqualTo(String value) {
            addCriterion("LEAGUE_NO =", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoNotEqualTo(String value) {
            addCriterion("LEAGUE_NO <>", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoGreaterThan(String value) {
            addCriterion("LEAGUE_NO >", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoGreaterThanOrEqualTo(String value) {
            addCriterion("LEAGUE_NO >=", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoLessThan(String value) {
            addCriterion("LEAGUE_NO <", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoLessThanOrEqualTo(String value) {
            addCriterion("LEAGUE_NO <=", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoLike(String value) {
            addCriterion("LEAGUE_NO like", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoNotLike(String value) {
            addCriterion("LEAGUE_NO not like", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoIn(List<String> values) {
            addCriterion("LEAGUE_NO in", values, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoNotIn(List<String> values) {
            addCriterion("LEAGUE_NO not in", values, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoBetween(String value1, String value2) {
            addCriterion("LEAGUE_NO between", value1, value2, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoNotBetween(String value1, String value2) {
            addCriterion("LEAGUE_NO not between", value1, value2, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNameIsNull() {
            addCriterion("LEAGUE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLeagueNameIsNotNull() {
            addCriterion("LEAGUE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLeagueNameEqualTo(String value) {
            addCriterion("LEAGUE_NAME =", value, "leagueName");
            return (Criteria) this;
        }

        public Criteria andLeagueNameNotEqualTo(String value) {
            addCriterion("LEAGUE_NAME <>", value, "leagueName");
            return (Criteria) this;
        }

        public Criteria andLeagueNameGreaterThan(String value) {
            addCriterion("LEAGUE_NAME >", value, "leagueName");
            return (Criteria) this;
        }

        public Criteria andLeagueNameGreaterThanOrEqualTo(String value) {
            addCriterion("LEAGUE_NAME >=", value, "leagueName");
            return (Criteria) this;
        }

        public Criteria andLeagueNameLessThan(String value) {
            addCriterion("LEAGUE_NAME <", value, "leagueName");
            return (Criteria) this;
        }

        public Criteria andLeagueNameLessThanOrEqualTo(String value) {
            addCriterion("LEAGUE_NAME <=", value, "leagueName");
            return (Criteria) this;
        }

        public Criteria andLeagueNameLike(String value) {
            addCriterion("LEAGUE_NAME like", value, "leagueName");
            return (Criteria) this;
        }

        public Criteria andLeagueNameNotLike(String value) {
            addCriterion("LEAGUE_NAME not like", value, "leagueName");
            return (Criteria) this;
        }

        public Criteria andLeagueNameIn(List<String> values) {
            addCriterion("LEAGUE_NAME in", values, "leagueName");
            return (Criteria) this;
        }

        public Criteria andLeagueNameNotIn(List<String> values) {
            addCriterion("LEAGUE_NAME not in", values, "leagueName");
            return (Criteria) this;
        }

        public Criteria andLeagueNameBetween(String value1, String value2) {
            addCriterion("LEAGUE_NAME between", value1, value2, "leagueName");
            return (Criteria) this;
        }

        public Criteria andLeagueNameNotBetween(String value1, String value2) {
            addCriterion("LEAGUE_NAME not between", value1, value2, "leagueName");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameIsNull() {
            addCriterion("LEAGUE_SHORT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameIsNotNull() {
            addCriterion("LEAGUE_SHORT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameEqualTo(String value) {
            addCriterion("LEAGUE_SHORT_NAME =", value, "leagueShortName");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameNotEqualTo(String value) {
            addCriterion("LEAGUE_SHORT_NAME <>", value, "leagueShortName");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameGreaterThan(String value) {
            addCriterion("LEAGUE_SHORT_NAME >", value, "leagueShortName");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("LEAGUE_SHORT_NAME >=", value, "leagueShortName");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameLessThan(String value) {
            addCriterion("LEAGUE_SHORT_NAME <", value, "leagueShortName");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameLessThanOrEqualTo(String value) {
            addCriterion("LEAGUE_SHORT_NAME <=", value, "leagueShortName");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameLike(String value) {
            addCriterion("LEAGUE_SHORT_NAME like", value, "leagueShortName");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameNotLike(String value) {
            addCriterion("LEAGUE_SHORT_NAME not like", value, "leagueShortName");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameIn(List<String> values) {
            addCriterion("LEAGUE_SHORT_NAME in", values, "leagueShortName");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameNotIn(List<String> values) {
            addCriterion("LEAGUE_SHORT_NAME not in", values, "leagueShortName");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameBetween(String value1, String value2) {
            addCriterion("LEAGUE_SHORT_NAME between", value1, value2, "leagueShortName");
            return (Criteria) this;
        }

        public Criteria andLeagueShortNameNotBetween(String value1, String value2) {
            addCriterion("LEAGUE_SHORT_NAME not between", value1, value2, "leagueShortName");
            return (Criteria) this;
        }

        public Criteria andEventTypeIsNull() {
            addCriterion("EVENT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andEventTypeIsNotNull() {
            addCriterion("EVENT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andEventTypeEqualTo(String value) {
            addCriterion("EVENT_TYPE =", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotEqualTo(String value) {
            addCriterion("EVENT_TYPE <>", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeGreaterThan(String value) {
            addCriterion("EVENT_TYPE >", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeGreaterThanOrEqualTo(String value) {
            addCriterion("EVENT_TYPE >=", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeLessThan(String value) {
            addCriterion("EVENT_TYPE <", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeLessThanOrEqualTo(String value) {
            addCriterion("EVENT_TYPE <=", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeLike(String value) {
            addCriterion("EVENT_TYPE like", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotLike(String value) {
            addCriterion("EVENT_TYPE not like", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeIn(List<String> values) {
            addCriterion("EVENT_TYPE in", values, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotIn(List<String> values) {
            addCriterion("EVENT_TYPE not in", values, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeBetween(String value1, String value2) {
            addCriterion("EVENT_TYPE between", value1, value2, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotBetween(String value1, String value2) {
            addCriterion("EVENT_TYPE not between", value1, value2, "eventType");
            return (Criteria) this;
        }

        public Criteria andContinentIsNull() {
            addCriterion("CONTINENT is null");
            return (Criteria) this;
        }

        public Criteria andContinentIsNotNull() {
            addCriterion("CONTINENT is not null");
            return (Criteria) this;
        }

        public Criteria andContinentEqualTo(String value) {
            addCriterion("CONTINENT =", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentNotEqualTo(String value) {
            addCriterion("CONTINENT <>", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentGreaterThan(String value) {
            addCriterion("CONTINENT >", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentGreaterThanOrEqualTo(String value) {
            addCriterion("CONTINENT >=", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentLessThan(String value) {
            addCriterion("CONTINENT <", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentLessThanOrEqualTo(String value) {
            addCriterion("CONTINENT <=", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentLike(String value) {
            addCriterion("CONTINENT like", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentNotLike(String value) {
            addCriterion("CONTINENT not like", value, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentIn(List<String> values) {
            addCriterion("CONTINENT in", values, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentNotIn(List<String> values) {
            addCriterion("CONTINENT not in", values, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentBetween(String value1, String value2) {
            addCriterion("CONTINENT between", value1, value2, "continent");
            return (Criteria) this;
        }

        public Criteria andContinentNotBetween(String value1, String value2) {
            addCriterion("CONTINENT not between", value1, value2, "continent");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("COUNTRY is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("COUNTRY is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("COUNTRY =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("COUNTRY <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("COUNTRY >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("COUNTRY >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("COUNTRY <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("COUNTRY <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("COUNTRY like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("COUNTRY not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("COUNTRY in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("COUNTRY not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("COUNTRY between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("COUNTRY not between", value1, value2, "country");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_league_info
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 03 11:08:15 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_league_info
     *
     * @mbggenerated Wed Feb 03 11:08:15 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}