package com.eastng.football.core.entity.match;

import java.util.Date;

public class LeagueSeason {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_season.ID
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_season.SEASON_NO
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    private String seasonNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_season.SEASON_NAME
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    private String seasonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_season.LEAGUE_NO
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    private String leagueNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_season.SEASON_BEGIN_DATE
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    private Date seasonBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_season.SEASON_END_DATE
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    private Date seasonEndDate;

    private String leagueShortName;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_season.ID
     *
     * @return the value of t_league_season.ID
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_season.ID
     *
     * @param id the value for t_league_season.ID
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_season.SEASON_NO
     *
     * @return the value of t_league_season.SEASON_NO
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    public String getSeasonNo() {
        return seasonNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_season.SEASON_NO
     *
     * @param seasonNo the value for t_league_season.SEASON_NO
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    public void setSeasonNo(String seasonNo) {
        this.seasonNo = seasonNo == null ? null : seasonNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_season.SEASON_NAME
     *
     * @return the value of t_league_season.SEASON_NAME
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    public String getSeasonName() {
        return seasonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_season.SEASON_NAME
     *
     * @param seasonName the value for t_league_season.SEASON_NAME
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    public void setSeasonName(String seasonName) {
        this.seasonName = seasonName == null ? null : seasonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_season.LEAGUE_NO
     *
     * @return the value of t_league_season.LEAGUE_NO
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    public String getLeagueNo() {
        return leagueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_season.LEAGUE_NO
     *
     * @param leagueNo the value for t_league_season.LEAGUE_NO
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    public void setLeagueNo(String leagueNo) {
        this.leagueNo = leagueNo == null ? null : leagueNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_season.SEASON_BEGIN_DATE
     *
     * @return the value of t_league_season.SEASON_BEGIN_DATE
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    public Date getSeasonBeginDate() {
        return seasonBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_season.SEASON_BEGIN_DATE
     *
     * @param seasonBeginDate the value for t_league_season.SEASON_BEGIN_DATE
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    public void setSeasonBeginDate(Date seasonBeginDate) {
        this.seasonBeginDate = seasonBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_season.SEASON_END_DATE
     *
     * @return the value of t_league_season.SEASON_END_DATE
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    public Date getSeasonEndDate() {
        return seasonEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_season.SEASON_END_DATE
     *
     * @param seasonEndDate the value for t_league_season.SEASON_END_DATE
     *
     * @mbggenerated Wed Aug 10 17:30:13 CST 2016
     */
    public void setSeasonEndDate(Date seasonEndDate) {
        this.seasonEndDate = seasonEndDate;
    }

	public String getLeagueShortName() {
		return leagueShortName;
	}

	public void setLeagueShortName(String leagueShortName) {
		this.leagueShortName = leagueShortName;
	}
    
}