package com.eastng.football.core.entity.match;

public class LeagueInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_info.ID
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_info.LEAGUE_NO
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    private String leagueNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_info.LEAGUE_NAME
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    private String leagueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_info.LEAGUE_SHORT_NAME
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    private String leagueShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_info.EVENT_TYPE
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    private String eventType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_info.CONTINENT
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    private String continent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_league_info.COUNTRY
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    private String country;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_info.ID
     *
     * @return the value of t_league_info.ID
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_info.ID
     *
     * @param id the value for t_league_info.ID
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_info.LEAGUE_NO
     *
     * @return the value of t_league_info.LEAGUE_NO
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public String getLeagueNo() {
        return leagueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_info.LEAGUE_NO
     *
     * @param leagueNo the value for t_league_info.LEAGUE_NO
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public void setLeagueNo(String leagueNo) {
        this.leagueNo = leagueNo == null ? null : leagueNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_info.LEAGUE_NAME
     *
     * @return the value of t_league_info.LEAGUE_NAME
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public String getLeagueName() {
        return leagueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_info.LEAGUE_NAME
     *
     * @param leagueName the value for t_league_info.LEAGUE_NAME
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public void setLeagueName(String leagueName) {
        this.leagueName = leagueName == null ? null : leagueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_info.LEAGUE_SHORT_NAME
     *
     * @return the value of t_league_info.LEAGUE_SHORT_NAME
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public String getLeagueShortName() {
        return leagueShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_info.LEAGUE_SHORT_NAME
     *
     * @param leagueShortName the value for t_league_info.LEAGUE_SHORT_NAME
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public void setLeagueShortName(String leagueShortName) {
        this.leagueShortName = leagueShortName == null ? null : leagueShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_info.EVENT_TYPE
     *
     * @return the value of t_league_info.EVENT_TYPE
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_info.EVENT_TYPE
     *
     * @param eventType the value for t_league_info.EVENT_TYPE
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public void setEventType(String eventType) {
        this.eventType = eventType == null ? null : eventType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_info.CONTINENT
     *
     * @return the value of t_league_info.CONTINENT
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public String getContinent() {
        return continent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_info.CONTINENT
     *
     * @param continent the value for t_league_info.CONTINENT
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public void setContinent(String continent) {
        this.continent = continent == null ? null : continent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_league_info.COUNTRY
     *
     * @return the value of t_league_info.COUNTRY
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_league_info.COUNTRY
     *
     * @param country the value for t_league_info.COUNTRY
     *
     * @mbggenerated Mon Jan 04 14:55:38 CST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }
}