package com.eastng.football.core.entity.match;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MatchExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    public MatchExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMatchNoIsNull() {
            addCriterion("MATCH_NO is null");
            return (Criteria) this;
        }

        public Criteria andMatchNoIsNotNull() {
            addCriterion("MATCH_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMatchNoEqualTo(String value) {
            addCriterion("MATCH_NO =", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoNotEqualTo(String value) {
            addCriterion("MATCH_NO <>", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoGreaterThan(String value) {
            addCriterion("MATCH_NO >", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoGreaterThanOrEqualTo(String value) {
            addCriterion("MATCH_NO >=", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoLessThan(String value) {
            addCriterion("MATCH_NO <", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoLessThanOrEqualTo(String value) {
            addCriterion("MATCH_NO <=", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoLike(String value) {
            addCriterion("MATCH_NO like", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoNotLike(String value) {
            addCriterion("MATCH_NO not like", value, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoIn(List<String> values) {
            addCriterion("MATCH_NO in", values, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoNotIn(List<String> values) {
            addCriterion("MATCH_NO not in", values, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoBetween(String value1, String value2) {
            addCriterion("MATCH_NO between", value1, value2, "matchNo");
            return (Criteria) this;
        }

        public Criteria andMatchNoNotBetween(String value1, String value2) {
            addCriterion("MATCH_NO not between", value1, value2, "matchNo");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoIsNull() {
            addCriterion("HOST_TEAM_NO is null");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoIsNotNull() {
            addCriterion("HOST_TEAM_NO is not null");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoEqualTo(String value) {
            addCriterion("HOST_TEAM_NO =", value, "hostTeamNo");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoNotEqualTo(String value) {
            addCriterion("HOST_TEAM_NO <>", value, "hostTeamNo");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoGreaterThan(String value) {
            addCriterion("HOST_TEAM_NO >", value, "hostTeamNo");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoGreaterThanOrEqualTo(String value) {
            addCriterion("HOST_TEAM_NO >=", value, "hostTeamNo");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoLessThan(String value) {
            addCriterion("HOST_TEAM_NO <", value, "hostTeamNo");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoLessThanOrEqualTo(String value) {
            addCriterion("HOST_TEAM_NO <=", value, "hostTeamNo");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoLike(String value) {
            addCriterion("HOST_TEAM_NO like", value, "hostTeamNo");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoNotLike(String value) {
            addCriterion("HOST_TEAM_NO not like", value, "hostTeamNo");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoIn(List<String> values) {
            addCriterion("HOST_TEAM_NO in", values, "hostTeamNo");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoNotIn(List<String> values) {
            addCriterion("HOST_TEAM_NO not in", values, "hostTeamNo");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoBetween(String value1, String value2) {
            addCriterion("HOST_TEAM_NO between", value1, value2, "hostTeamNo");
            return (Criteria) this;
        }

        public Criteria andHostTeamNoNotBetween(String value1, String value2) {
            addCriterion("HOST_TEAM_NO not between", value1, value2, "hostTeamNo");
            return (Criteria) this;
        }

        public Criteria andHostShortNameIsNull() {
            addCriterion("HOST_SHORT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andHostShortNameIsNotNull() {
            addCriterion("HOST_SHORT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andHostShortNameEqualTo(String value) {
            addCriterion("HOST_SHORT_NAME =", value, "hostShortName");
            return (Criteria) this;
        }

        public Criteria andHostShortNameNotEqualTo(String value) {
            addCriterion("HOST_SHORT_NAME <>", value, "hostShortName");
            return (Criteria) this;
        }

        public Criteria andHostShortNameGreaterThan(String value) {
            addCriterion("HOST_SHORT_NAME >", value, "hostShortName");
            return (Criteria) this;
        }

        public Criteria andHostShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("HOST_SHORT_NAME >=", value, "hostShortName");
            return (Criteria) this;
        }

        public Criteria andHostShortNameLessThan(String value) {
            addCriterion("HOST_SHORT_NAME <", value, "hostShortName");
            return (Criteria) this;
        }

        public Criteria andHostShortNameLessThanOrEqualTo(String value) {
            addCriterion("HOST_SHORT_NAME <=", value, "hostShortName");
            return (Criteria) this;
        }

        public Criteria andHostShortNameLike(String value) {
            addCriterion("HOST_SHORT_NAME like", value, "hostShortName");
            return (Criteria) this;
        }

        public Criteria andHostShortNameNotLike(String value) {
            addCriterion("HOST_SHORT_NAME not like", value, "hostShortName");
            return (Criteria) this;
        }

        public Criteria andHostShortNameIn(List<String> values) {
            addCriterion("HOST_SHORT_NAME in", values, "hostShortName");
            return (Criteria) this;
        }

        public Criteria andHostShortNameNotIn(List<String> values) {
            addCriterion("HOST_SHORT_NAME not in", values, "hostShortName");
            return (Criteria) this;
        }

        public Criteria andHostShortNameBetween(String value1, String value2) {
            addCriterion("HOST_SHORT_NAME between", value1, value2, "hostShortName");
            return (Criteria) this;
        }

        public Criteria andHostShortNameNotBetween(String value1, String value2) {
            addCriterion("HOST_SHORT_NAME not between", value1, value2, "hostShortName");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoIsNull() {
            addCriterion("GUEST_TEAM_NO is null");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoIsNotNull() {
            addCriterion("GUEST_TEAM_NO is not null");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoEqualTo(String value) {
            addCriterion("GUEST_TEAM_NO =", value, "guestTeamNo");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoNotEqualTo(String value) {
            addCriterion("GUEST_TEAM_NO <>", value, "guestTeamNo");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoGreaterThan(String value) {
            addCriterion("GUEST_TEAM_NO >", value, "guestTeamNo");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoGreaterThanOrEqualTo(String value) {
            addCriterion("GUEST_TEAM_NO >=", value, "guestTeamNo");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoLessThan(String value) {
            addCriterion("GUEST_TEAM_NO <", value, "guestTeamNo");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoLessThanOrEqualTo(String value) {
            addCriterion("GUEST_TEAM_NO <=", value, "guestTeamNo");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoLike(String value) {
            addCriterion("GUEST_TEAM_NO like", value, "guestTeamNo");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoNotLike(String value) {
            addCriterion("GUEST_TEAM_NO not like", value, "guestTeamNo");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoIn(List<String> values) {
            addCriterion("GUEST_TEAM_NO in", values, "guestTeamNo");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoNotIn(List<String> values) {
            addCriterion("GUEST_TEAM_NO not in", values, "guestTeamNo");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoBetween(String value1, String value2) {
            addCriterion("GUEST_TEAM_NO between", value1, value2, "guestTeamNo");
            return (Criteria) this;
        }

        public Criteria andGuestTeamNoNotBetween(String value1, String value2) {
            addCriterion("GUEST_TEAM_NO not between", value1, value2, "guestTeamNo");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameIsNull() {
            addCriterion("GUEST_SHORT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameIsNotNull() {
            addCriterion("GUEST_SHORT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameEqualTo(String value) {
            addCriterion("GUEST_SHORT_NAME =", value, "guestShortName");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameNotEqualTo(String value) {
            addCriterion("GUEST_SHORT_NAME <>", value, "guestShortName");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameGreaterThan(String value) {
            addCriterion("GUEST_SHORT_NAME >", value, "guestShortName");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameGreaterThanOrEqualTo(String value) {
            addCriterion("GUEST_SHORT_NAME >=", value, "guestShortName");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameLessThan(String value) {
            addCriterion("GUEST_SHORT_NAME <", value, "guestShortName");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameLessThanOrEqualTo(String value) {
            addCriterion("GUEST_SHORT_NAME <=", value, "guestShortName");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameLike(String value) {
            addCriterion("GUEST_SHORT_NAME like", value, "guestShortName");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameNotLike(String value) {
            addCriterion("GUEST_SHORT_NAME not like", value, "guestShortName");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameIn(List<String> values) {
            addCriterion("GUEST_SHORT_NAME in", values, "guestShortName");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameNotIn(List<String> values) {
            addCriterion("GUEST_SHORT_NAME not in", values, "guestShortName");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameBetween(String value1, String value2) {
            addCriterion("GUEST_SHORT_NAME between", value1, value2, "guestShortName");
            return (Criteria) this;
        }

        public Criteria andGuestShortNameNotBetween(String value1, String value2) {
            addCriterion("GUEST_SHORT_NAME not between", value1, value2, "guestShortName");
            return (Criteria) this;
        }

        public Criteria andLeagueNoIsNull() {
            addCriterion("LEAGUE_NO is null");
            return (Criteria) this;
        }

        public Criteria andLeagueNoIsNotNull() {
            addCriterion("LEAGUE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andLeagueNoEqualTo(String value) {
            addCriterion("LEAGUE_NO =", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoNotEqualTo(String value) {
            addCriterion("LEAGUE_NO <>", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoGreaterThan(String value) {
            addCriterion("LEAGUE_NO >", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoGreaterThanOrEqualTo(String value) {
            addCriterion("LEAGUE_NO >=", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoLessThan(String value) {
            addCriterion("LEAGUE_NO <", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoLessThanOrEqualTo(String value) {
            addCriterion("LEAGUE_NO <=", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoLike(String value) {
            addCriterion("LEAGUE_NO like", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoNotLike(String value) {
            addCriterion("LEAGUE_NO not like", value, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoIn(List<String> values) {
            addCriterion("LEAGUE_NO in", values, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoNotIn(List<String> values) {
            addCriterion("LEAGUE_NO not in", values, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoBetween(String value1, String value2) {
            addCriterion("LEAGUE_NO between", value1, value2, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andLeagueNoNotBetween(String value1, String value2) {
            addCriterion("LEAGUE_NO not between", value1, value2, "leagueNo");
            return (Criteria) this;
        }

        public Criteria andSeasonNameIsNull() {
            addCriterion("SEASON_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSeasonNameIsNotNull() {
            addCriterion("SEASON_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSeasonNameEqualTo(String value) {
            addCriterion("SEASON_NAME =", value, "seasonName");
            return (Criteria) this;
        }

        public Criteria andSeasonNameNotEqualTo(String value) {
            addCriterion("SEASON_NAME <>", value, "seasonName");
            return (Criteria) this;
        }

        public Criteria andSeasonNameGreaterThan(String value) {
            addCriterion("SEASON_NAME >", value, "seasonName");
            return (Criteria) this;
        }

        public Criteria andSeasonNameGreaterThanOrEqualTo(String value) {
            addCriterion("SEASON_NAME >=", value, "seasonName");
            return (Criteria) this;
        }

        public Criteria andSeasonNameLessThan(String value) {
            addCriterion("SEASON_NAME <", value, "seasonName");
            return (Criteria) this;
        }

        public Criteria andSeasonNameLessThanOrEqualTo(String value) {
            addCriterion("SEASON_NAME <=", value, "seasonName");
            return (Criteria) this;
        }

        public Criteria andSeasonNameLike(String value) {
            addCriterion("SEASON_NAME like", value, "seasonName");
            return (Criteria) this;
        }

        public Criteria andSeasonNameNotLike(String value) {
            addCriterion("SEASON_NAME not like", value, "seasonName");
            return (Criteria) this;
        }

        public Criteria andSeasonNameIn(List<String> values) {
            addCriterion("SEASON_NAME in", values, "seasonName");
            return (Criteria) this;
        }

        public Criteria andSeasonNameNotIn(List<String> values) {
            addCriterion("SEASON_NAME not in", values, "seasonName");
            return (Criteria) this;
        }

        public Criteria andSeasonNameBetween(String value1, String value2) {
            addCriterion("SEASON_NAME between", value1, value2, "seasonName");
            return (Criteria) this;
        }

        public Criteria andSeasonNameNotBetween(String value1, String value2) {
            addCriterion("SEASON_NAME not between", value1, value2, "seasonName");
            return (Criteria) this;
        }

        public Criteria andMatchTimeIsNull() {
            addCriterion("MATCH_TIME is null");
            return (Criteria) this;
        }

        public Criteria andMatchTimeIsNotNull() {
            addCriterion("MATCH_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andMatchTimeEqualTo(Date value) {
            addCriterion("MATCH_TIME =", value, "matchTime");
            return (Criteria) this;
        }

        public Criteria andMatchTimeNotEqualTo(Date value) {
            addCriterion("MATCH_TIME <>", value, "matchTime");
            return (Criteria) this;
        }

        public Criteria andMatchTimeGreaterThan(Date value) {
            addCriterion("MATCH_TIME >", value, "matchTime");
            return (Criteria) this;
        }

        public Criteria andMatchTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MATCH_TIME >=", value, "matchTime");
            return (Criteria) this;
        }

        public Criteria andMatchTimeLessThan(Date value) {
            addCriterion("MATCH_TIME <", value, "matchTime");
            return (Criteria) this;
        }

        public Criteria andMatchTimeLessThanOrEqualTo(Date value) {
            addCriterion("MATCH_TIME <=", value, "matchTime");
            return (Criteria) this;
        }

        public Criteria andMatchTimeIn(List<Date> values) {
            addCriterion("MATCH_TIME in", values, "matchTime");
            return (Criteria) this;
        }

        public Criteria andMatchTimeNotIn(List<Date> values) {
            addCriterion("MATCH_TIME not in", values, "matchTime");
            return (Criteria) this;
        }

        public Criteria andMatchTimeBetween(Date value1, Date value2) {
            addCriterion("MATCH_TIME between", value1, value2, "matchTime");
            return (Criteria) this;
        }

        public Criteria andMatchTimeNotBetween(Date value1, Date value2) {
            addCriterion("MATCH_TIME not between", value1, value2, "matchTime");
            return (Criteria) this;
        }

        public Criteria andRoundIsNull() {
            addCriterion("ROUND is null");
            return (Criteria) this;
        }

        public Criteria andRoundIsNotNull() {
            addCriterion("ROUND is not null");
            return (Criteria) this;
        }

        public Criteria andRoundEqualTo(Integer value) {
            addCriterion("ROUND =", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundNotEqualTo(Integer value) {
            addCriterion("ROUND <>", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundGreaterThan(Integer value) {
            addCriterion("ROUND >", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundGreaterThanOrEqualTo(Integer value) {
            addCriterion("ROUND >=", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundLessThan(Integer value) {
            addCriterion("ROUND <", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundLessThanOrEqualTo(Integer value) {
            addCriterion("ROUND <=", value, "round");
            return (Criteria) this;
        }

        public Criteria andRoundIn(List<Integer> values) {
            addCriterion("ROUND in", values, "round");
            return (Criteria) this;
        }

        public Criteria andRoundNotIn(List<Integer> values) {
            addCriterion("ROUND not in", values, "round");
            return (Criteria) this;
        }

        public Criteria andRoundBetween(Integer value1, Integer value2) {
            addCriterion("ROUND between", value1, value2, "round");
            return (Criteria) this;
        }

        public Criteria andRoundNotBetween(Integer value1, Integer value2) {
            addCriterion("ROUND not between", value1, value2, "round");
            return (Criteria) this;
        }

        public Criteria andHostGoalIsNull() {
            addCriterion("HOST_GOAL is null");
            return (Criteria) this;
        }

        public Criteria andHostGoalIsNotNull() {
            addCriterion("HOST_GOAL is not null");
            return (Criteria) this;
        }

        public Criteria andHostGoalEqualTo(Integer value) {
            addCriterion("HOST_GOAL =", value, "hostGoal");
            return (Criteria) this;
        }

        public Criteria andHostGoalNotEqualTo(Integer value) {
            addCriterion("HOST_GOAL <>", value, "hostGoal");
            return (Criteria) this;
        }

        public Criteria andHostGoalGreaterThan(Integer value) {
            addCriterion("HOST_GOAL >", value, "hostGoal");
            return (Criteria) this;
        }

        public Criteria andHostGoalGreaterThanOrEqualTo(Integer value) {
            addCriterion("HOST_GOAL >=", value, "hostGoal");
            return (Criteria) this;
        }

        public Criteria andHostGoalLessThan(Integer value) {
            addCriterion("HOST_GOAL <", value, "hostGoal");
            return (Criteria) this;
        }

        public Criteria andHostGoalLessThanOrEqualTo(Integer value) {
            addCriterion("HOST_GOAL <=", value, "hostGoal");
            return (Criteria) this;
        }

        public Criteria andHostGoalIn(List<Integer> values) {
            addCriterion("HOST_GOAL in", values, "hostGoal");
            return (Criteria) this;
        }

        public Criteria andHostGoalNotIn(List<Integer> values) {
            addCriterion("HOST_GOAL not in", values, "hostGoal");
            return (Criteria) this;
        }

        public Criteria andHostGoalBetween(Integer value1, Integer value2) {
            addCriterion("HOST_GOAL between", value1, value2, "hostGoal");
            return (Criteria) this;
        }

        public Criteria andHostGoalNotBetween(Integer value1, Integer value2) {
            addCriterion("HOST_GOAL not between", value1, value2, "hostGoal");
            return (Criteria) this;
        }

        public Criteria andGuestGoalIsNull() {
            addCriterion("GUEST_GOAL is null");
            return (Criteria) this;
        }

        public Criteria andGuestGoalIsNotNull() {
            addCriterion("GUEST_GOAL is not null");
            return (Criteria) this;
        }

        public Criteria andGuestGoalEqualTo(Integer value) {
            addCriterion("GUEST_GOAL =", value, "guestGoal");
            return (Criteria) this;
        }

        public Criteria andGuestGoalNotEqualTo(Integer value) {
            addCriterion("GUEST_GOAL <>", value, "guestGoal");
            return (Criteria) this;
        }

        public Criteria andGuestGoalGreaterThan(Integer value) {
            addCriterion("GUEST_GOAL >", value, "guestGoal");
            return (Criteria) this;
        }

        public Criteria andGuestGoalGreaterThanOrEqualTo(Integer value) {
            addCriterion("GUEST_GOAL >=", value, "guestGoal");
            return (Criteria) this;
        }

        public Criteria andGuestGoalLessThan(Integer value) {
            addCriterion("GUEST_GOAL <", value, "guestGoal");
            return (Criteria) this;
        }

        public Criteria andGuestGoalLessThanOrEqualTo(Integer value) {
            addCriterion("GUEST_GOAL <=", value, "guestGoal");
            return (Criteria) this;
        }

        public Criteria andGuestGoalIn(List<Integer> values) {
            addCriterion("GUEST_GOAL in", values, "guestGoal");
            return (Criteria) this;
        }

        public Criteria andGuestGoalNotIn(List<Integer> values) {
            addCriterion("GUEST_GOAL not in", values, "guestGoal");
            return (Criteria) this;
        }

        public Criteria andGuestGoalBetween(Integer value1, Integer value2) {
            addCriterion("GUEST_GOAL between", value1, value2, "guestGoal");
            return (Criteria) this;
        }

        public Criteria andGuestGoalNotBetween(Integer value1, Integer value2) {
            addCriterion("GUEST_GOAL not between", value1, value2, "guestGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeHostGoalIsNull() {
            addCriterion("HALF_TIME_HOST_GOAL is null");
            return (Criteria) this;
        }

        public Criteria andHalfTimeHostGoalIsNotNull() {
            addCriterion("HALF_TIME_HOST_GOAL is not null");
            return (Criteria) this;
        }

        public Criteria andHalfTimeHostGoalEqualTo(Integer value) {
            addCriterion("HALF_TIME_HOST_GOAL =", value, "halfTimeHostGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeHostGoalNotEqualTo(Integer value) {
            addCriterion("HALF_TIME_HOST_GOAL <>", value, "halfTimeHostGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeHostGoalGreaterThan(Integer value) {
            addCriterion("HALF_TIME_HOST_GOAL >", value, "halfTimeHostGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeHostGoalGreaterThanOrEqualTo(Integer value) {
            addCriterion("HALF_TIME_HOST_GOAL >=", value, "halfTimeHostGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeHostGoalLessThan(Integer value) {
            addCriterion("HALF_TIME_HOST_GOAL <", value, "halfTimeHostGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeHostGoalLessThanOrEqualTo(Integer value) {
            addCriterion("HALF_TIME_HOST_GOAL <=", value, "halfTimeHostGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeHostGoalIn(List<Integer> values) {
            addCriterion("HALF_TIME_HOST_GOAL in", values, "halfTimeHostGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeHostGoalNotIn(List<Integer> values) {
            addCriterion("HALF_TIME_HOST_GOAL not in", values, "halfTimeHostGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeHostGoalBetween(Integer value1, Integer value2) {
            addCriterion("HALF_TIME_HOST_GOAL between", value1, value2, "halfTimeHostGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeHostGoalNotBetween(Integer value1, Integer value2) {
            addCriterion("HALF_TIME_HOST_GOAL not between", value1, value2, "halfTimeHostGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeGuestGoalIsNull() {
            addCriterion("HALF_TIME_GUEST_GOAL is null");
            return (Criteria) this;
        }

        public Criteria andHalfTimeGuestGoalIsNotNull() {
            addCriterion("HALF_TIME_GUEST_GOAL is not null");
            return (Criteria) this;
        }

        public Criteria andHalfTimeGuestGoalEqualTo(Integer value) {
            addCriterion("HALF_TIME_GUEST_GOAL =", value, "halfTimeGuestGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeGuestGoalNotEqualTo(Integer value) {
            addCriterion("HALF_TIME_GUEST_GOAL <>", value, "halfTimeGuestGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeGuestGoalGreaterThan(Integer value) {
            addCriterion("HALF_TIME_GUEST_GOAL >", value, "halfTimeGuestGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeGuestGoalGreaterThanOrEqualTo(Integer value) {
            addCriterion("HALF_TIME_GUEST_GOAL >=", value, "halfTimeGuestGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeGuestGoalLessThan(Integer value) {
            addCriterion("HALF_TIME_GUEST_GOAL <", value, "halfTimeGuestGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeGuestGoalLessThanOrEqualTo(Integer value) {
            addCriterion("HALF_TIME_GUEST_GOAL <=", value, "halfTimeGuestGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeGuestGoalIn(List<Integer> values) {
            addCriterion("HALF_TIME_GUEST_GOAL in", values, "halfTimeGuestGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeGuestGoalNotIn(List<Integer> values) {
            addCriterion("HALF_TIME_GUEST_GOAL not in", values, "halfTimeGuestGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeGuestGoalBetween(Integer value1, Integer value2) {
            addCriterion("HALF_TIME_GUEST_GOAL between", value1, value2, "halfTimeGuestGoal");
            return (Criteria) this;
        }

        public Criteria andHalfTimeGuestGoalNotBetween(Integer value1, Integer value2) {
            addCriterion("HALF_TIME_GUEST_GOAL not between", value1, value2, "halfTimeGuestGoal");
            return (Criteria) this;
        }

        public Criteria andMatchStatusIsNull() {
            addCriterion("MATCH_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andMatchStatusIsNotNull() {
            addCriterion("MATCH_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andMatchStatusEqualTo(String value) {
            addCriterion("MATCH_STATUS =", value, "matchStatus");
            return (Criteria) this;
        }

        public Criteria andMatchStatusNotEqualTo(String value) {
            addCriterion("MATCH_STATUS <>", value, "matchStatus");
            return (Criteria) this;
        }

        public Criteria andMatchStatusGreaterThan(String value) {
            addCriterion("MATCH_STATUS >", value, "matchStatus");
            return (Criteria) this;
        }

        public Criteria andMatchStatusGreaterThanOrEqualTo(String value) {
            addCriterion("MATCH_STATUS >=", value, "matchStatus");
            return (Criteria) this;
        }

        public Criteria andMatchStatusLessThan(String value) {
            addCriterion("MATCH_STATUS <", value, "matchStatus");
            return (Criteria) this;
        }

        public Criteria andMatchStatusLessThanOrEqualTo(String value) {
            addCriterion("MATCH_STATUS <=", value, "matchStatus");
            return (Criteria) this;
        }

        public Criteria andMatchStatusLike(String value) {
            addCriterion("MATCH_STATUS like", value, "matchStatus");
            return (Criteria) this;
        }

        public Criteria andMatchStatusNotLike(String value) {
            addCriterion("MATCH_STATUS not like", value, "matchStatus");
            return (Criteria) this;
        }

        public Criteria andMatchStatusIn(List<String> values) {
            addCriterion("MATCH_STATUS in", values, "matchStatus");
            return (Criteria) this;
        }

        public Criteria andMatchStatusNotIn(List<String> values) {
            addCriterion("MATCH_STATUS not in", values, "matchStatus");
            return (Criteria) this;
        }

        public Criteria andMatchStatusBetween(String value1, String value2) {
            addCriterion("MATCH_STATUS between", value1, value2, "matchStatus");
            return (Criteria) this;
        }

        public Criteria andMatchStatusNotBetween(String value1, String value2) {
            addCriterion("MATCH_STATUS not between", value1, value2, "matchStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_match
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 06 17:37:29 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_match
     *
     * @mbggenerated Wed Jan 06 17:37:29 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}