package com.eastng.football.core.entity.match;

public class TeamLeagueSeason {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.ID
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.TEAM_NO
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private String teamNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.TEAM_SHORT_NAME
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private String teamShortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.LEAGUE_NO
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private String leagueNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.SEASON_NAME
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private String seasonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.ROUND
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer round;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.WIN
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer win;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.DRAW
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer draw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.LOSE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer lose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.GOALS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer goals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.POINTS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer points;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.FUMBLE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer fumble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.HOST_HAVE_MATCH
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer hostHaveMatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.HOST_WIN
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer hostWin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.HOST_DRAW
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer hostDraw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.HOST_LOSE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer hostLose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.HOST_GOALS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer hostGoals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.HOST_FUMBLE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer hostFumble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.HOST_POINTS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer hostPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.GUEST_HAVE_MATCH
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer guestHaveMatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.GUEST_WIN
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer guestWin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.GUEST_DRAW
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer guestDraw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.GUEST_LOSE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer guestLose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.GUEST_GOALS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer guestGoals;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.GUEST_FUMBLE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer guestFumble;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_team_league_season.GUEST_POINTS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    private Integer guestPoints;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.ID
     *
     * @return the value of t_team_league_season.ID
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.ID
     *
     * @param id the value for t_team_league_season.ID
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.TEAM_NO
     *
     * @return the value of t_team_league_season.TEAM_NO
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public String getTeamNo() {
        return teamNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.TEAM_NO
     *
     * @param teamNo the value for t_team_league_season.TEAM_NO
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setTeamNo(String teamNo) {
        this.teamNo = teamNo == null ? null : teamNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.TEAM_SHORT_NAME
     *
     * @return the value of t_team_league_season.TEAM_SHORT_NAME
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public String getTeamShortName() {
        return teamShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.TEAM_SHORT_NAME
     *
     * @param teamShortName the value for t_team_league_season.TEAM_SHORT_NAME
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setTeamShortName(String teamShortName) {
        this.teamShortName = teamShortName == null ? null : teamShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.LEAGUE_NO
     *
     * @return the value of t_team_league_season.LEAGUE_NO
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public String getLeagueNo() {
        return leagueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.LEAGUE_NO
     *
     * @param leagueNo the value for t_team_league_season.LEAGUE_NO
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setLeagueNo(String leagueNo) {
        this.leagueNo = leagueNo == null ? null : leagueNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.SEASON_NAME
     *
     * @return the value of t_team_league_season.SEASON_NAME
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public String getSeasonName() {
        return seasonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.SEASON_NAME
     *
     * @param seasonName the value for t_team_league_season.SEASON_NAME
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setSeasonName(String seasonName) {
        this.seasonName = seasonName == null ? null : seasonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.ROUND
     *
     * @return the value of t_team_league_season.ROUND
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getRound() {
        return round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.ROUND
     *
     * @param round the value for t_team_league_season.ROUND
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setRound(Integer round) {
        this.round = round;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.WIN
     *
     * @return the value of t_team_league_season.WIN
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getWin() {
        return win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.WIN
     *
     * @param win the value for t_team_league_season.WIN
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setWin(Integer win) {
        this.win = win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.DRAW
     *
     * @return the value of t_team_league_season.DRAW
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getDraw() {
        return draw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.DRAW
     *
     * @param draw the value for t_team_league_season.DRAW
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setDraw(Integer draw) {
        this.draw = draw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.LOSE
     *
     * @return the value of t_team_league_season.LOSE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getLose() {
        return lose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.LOSE
     *
     * @param lose the value for t_team_league_season.LOSE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setLose(Integer lose) {
        this.lose = lose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.GOALS
     *
     * @return the value of t_team_league_season.GOALS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getGoals() {
        return goals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.GOALS
     *
     * @param goals the value for t_team_league_season.GOALS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setGoals(Integer goals) {
        this.goals = goals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.POINTS
     *
     * @return the value of t_team_league_season.POINTS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.POINTS
     *
     * @param points the value for t_team_league_season.POINTS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.FUMBLE
     *
     * @return the value of t_team_league_season.FUMBLE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getFumble() {
        return fumble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.FUMBLE
     *
     * @param fumble the value for t_team_league_season.FUMBLE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setFumble(Integer fumble) {
        this.fumble = fumble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.HOST_HAVE_MATCH
     *
     * @return the value of t_team_league_season.HOST_HAVE_MATCH
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getHostHaveMatch() {
        return hostHaveMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.HOST_HAVE_MATCH
     *
     * @param hostHaveMatch the value for t_team_league_season.HOST_HAVE_MATCH
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setHostHaveMatch(Integer hostHaveMatch) {
        this.hostHaveMatch = hostHaveMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.HOST_WIN
     *
     * @return the value of t_team_league_season.HOST_WIN
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getHostWin() {
        return hostWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.HOST_WIN
     *
     * @param hostWin the value for t_team_league_season.HOST_WIN
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setHostWin(Integer hostWin) {
        this.hostWin = hostWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.HOST_DRAW
     *
     * @return the value of t_team_league_season.HOST_DRAW
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getHostDraw() {
        return hostDraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.HOST_DRAW
     *
     * @param hostDraw the value for t_team_league_season.HOST_DRAW
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setHostDraw(Integer hostDraw) {
        this.hostDraw = hostDraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.HOST_LOSE
     *
     * @return the value of t_team_league_season.HOST_LOSE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getHostLose() {
        return hostLose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.HOST_LOSE
     *
     * @param hostLose the value for t_team_league_season.HOST_LOSE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setHostLose(Integer hostLose) {
        this.hostLose = hostLose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.HOST_GOALS
     *
     * @return the value of t_team_league_season.HOST_GOALS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getHostGoals() {
        return hostGoals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.HOST_GOALS
     *
     * @param hostGoals the value for t_team_league_season.HOST_GOALS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setHostGoals(Integer hostGoals) {
        this.hostGoals = hostGoals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.HOST_FUMBLE
     *
     * @return the value of t_team_league_season.HOST_FUMBLE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getHostFumble() {
        return hostFumble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.HOST_FUMBLE
     *
     * @param hostFumble the value for t_team_league_season.HOST_FUMBLE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setHostFumble(Integer hostFumble) {
        this.hostFumble = hostFumble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.HOST_POINTS
     *
     * @return the value of t_team_league_season.HOST_POINTS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getHostPoints() {
        return hostPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.HOST_POINTS
     *
     * @param hostPoints the value for t_team_league_season.HOST_POINTS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setHostPoints(Integer hostPoints) {
        this.hostPoints = hostPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.GUEST_HAVE_MATCH
     *
     * @return the value of t_team_league_season.GUEST_HAVE_MATCH
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getGuestHaveMatch() {
        return guestHaveMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.GUEST_HAVE_MATCH
     *
     * @param guestHaveMatch the value for t_team_league_season.GUEST_HAVE_MATCH
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setGuestHaveMatch(Integer guestHaveMatch) {
        this.guestHaveMatch = guestHaveMatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.GUEST_WIN
     *
     * @return the value of t_team_league_season.GUEST_WIN
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getGuestWin() {
        return guestWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.GUEST_WIN
     *
     * @param guestWin the value for t_team_league_season.GUEST_WIN
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setGuestWin(Integer guestWin) {
        this.guestWin = guestWin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.GUEST_DRAW
     *
     * @return the value of t_team_league_season.GUEST_DRAW
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getGuestDraw() {
        return guestDraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.GUEST_DRAW
     *
     * @param guestDraw the value for t_team_league_season.GUEST_DRAW
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setGuestDraw(Integer guestDraw) {
        this.guestDraw = guestDraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.GUEST_LOSE
     *
     * @return the value of t_team_league_season.GUEST_LOSE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getGuestLose() {
        return guestLose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.GUEST_LOSE
     *
     * @param guestLose the value for t_team_league_season.GUEST_LOSE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setGuestLose(Integer guestLose) {
        this.guestLose = guestLose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.GUEST_GOALS
     *
     * @return the value of t_team_league_season.GUEST_GOALS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getGuestGoals() {
        return guestGoals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.GUEST_GOALS
     *
     * @param guestGoals the value for t_team_league_season.GUEST_GOALS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setGuestGoals(Integer guestGoals) {
        this.guestGoals = guestGoals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.GUEST_FUMBLE
     *
     * @return the value of t_team_league_season.GUEST_FUMBLE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getGuestFumble() {
        return guestFumble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.GUEST_FUMBLE
     *
     * @param guestFumble the value for t_team_league_season.GUEST_FUMBLE
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setGuestFumble(Integer guestFumble) {
        this.guestFumble = guestFumble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_team_league_season.GUEST_POINTS
     *
     * @return the value of t_team_league_season.GUEST_POINTS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public Integer getGuestPoints() {
        return guestPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_team_league_season.GUEST_POINTS
     *
     * @param guestPoints the value for t_team_league_season.GUEST_POINTS
     *
     * @mbggenerated Wed Jan 06 11:10:19 CST 2016
     */
    public void setGuestPoints(Integer guestPoints) {
        this.guestPoints = guestPoints;
    }
}