package com.eastng.football.core.entity.lottery;

import java.math.BigDecimal;
import java.util.Date;

public class Odds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_odds.ID
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_odds.MATCH_NO
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    private String matchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_odds.COMPANY
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_odds.CHANGE_TIME
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_odds.WIN
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    private BigDecimal win;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_odds.DRAW
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    private BigDecimal draw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_odds.LOSE
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    private BigDecimal lose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_odds.FIRST_ODDS
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    private String firstOdds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_odds.ID
     *
     * @return the value of t_odds.ID
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_odds.ID
     *
     * @param id the value for t_odds.ID
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_odds.MATCH_NO
     *
     * @return the value of t_odds.MATCH_NO
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public String getMatchNo() {
        return matchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_odds.MATCH_NO
     *
     * @param matchNo the value for t_odds.MATCH_NO
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public void setMatchNo(String matchNo) {
        this.matchNo = matchNo == null ? null : matchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_odds.COMPANY
     *
     * @return the value of t_odds.COMPANY
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_odds.COMPANY
     *
     * @param company the value for t_odds.COMPANY
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_odds.CHANGE_TIME
     *
     * @return the value of t_odds.CHANGE_TIME
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_odds.CHANGE_TIME
     *
     * @param changeTime the value for t_odds.CHANGE_TIME
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_odds.WIN
     *
     * @return the value of t_odds.WIN
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public BigDecimal getWin() {
        return win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_odds.WIN
     *
     * @param win the value for t_odds.WIN
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public void setWin(BigDecimal win) {
        this.win = win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_odds.DRAW
     *
     * @return the value of t_odds.DRAW
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public BigDecimal getDraw() {
        return draw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_odds.DRAW
     *
     * @param draw the value for t_odds.DRAW
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public void setDraw(BigDecimal draw) {
        this.draw = draw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_odds.LOSE
     *
     * @return the value of t_odds.LOSE
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public BigDecimal getLose() {
        return lose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_odds.LOSE
     *
     * @param lose the value for t_odds.LOSE
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public void setLose(BigDecimal lose) {
        this.lose = lose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_odds.FIRST_ODDS
     *
     * @return the value of t_odds.FIRST_ODDS
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public String getFirstOdds() {
        return firstOdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_odds.FIRST_ODDS
     *
     * @param firstOdds the value for t_odds.FIRST_ODDS
     *
     * @mbggenerated Sat Jan 09 15:20:46 CST 2016
     */
    public void setFirstOdds(String firstOdds) {
        this.firstOdds = firstOdds == null ? null : firstOdds.trim();
    }
}